Revert "Add oracle JVM 8"
DataDog/dd-trace-java-docker-build pull request #29
Opened 2021-05-19 20:29 UTC by tylerbenson

Reverts DataDog/dd-trace-java-docker-build#27

That build is not available anymore and now seems to require a login.

2021-05-19 20:48 UTC, devinsba approved these changes

2021-05-20 08:21 UTC, jbachorik commented
It would be better to update the link. Oracle removed the jdk8u281 download and replaced it with jdk8u291.

2021-05-20 09:02 UTC, jbachorik requested changes
I am going to block this change so it does not get merged by mistake.
The problem with Oracle JDK 8 download link is solved in #30

2021-05-20 13:34 UTC, jbachorik approved these changes

2021-05-20 13:50 UTC, tylerbenson commented
Looks like #30 can work... we just missed a small part of the URL that bypasses the login.

2021-05-20 13:50 UTC, closed without merging